import React from 'react'

const RequestCom = () => {
  return (
    <div className='text-white'>
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure quod inventore nam, vel dignissimos laboriosam fugit nihil consequatur dicta accusamus impedit, quas eligendi, fuga debitis cumque nesciunt. Earum quibusdam ducimus impedit esse amet mollitia, unde aperiam nihil, consequuntur maxime ad? Ullam recusandae dolorem fuga enim temporibus voluptate vero, similique esse incidunt et a magni unde vel magnam perspiciatis ea, quae ab sint cupiditate, voluptas culpa consequatur quo sed at? Rerum, accusantium voluptates nisi fuga hic dignissimos culpa architecto amet, praesentium eaque maxime omnis. Mollitia omnis, nisi debitis ex maiores architecto deleniti nam provident animi accusamus a nesciunt. Sapiente, consequatur tempore veritatis illo vel necessitatibus, rerum molestias officiis omnis placeat facere inventore voluptatum incidunt et hic doloremque, nesciunt commodi recusandae quae iusto nulla mollitia quasi. Ex reiciendis modi unde cumque similique facere a nam, quis impedit nisi. Veritatis aliquam, magni aspernatur maiores libero itaque autem a corrupti minus, minima ab sequi, excepturi possimus sit. Asperiores magni temporibus aliquid unde libero. Ad at blanditiis culpa odio? Beatae eius possimus optio qui placeat accusamus ullam quia, ut molestiae nostrum, error necessitatibus. Cum ea perferendis porro ducimus ad quae quasi repudiandae aliquid minima, ipsum iure praesentium odio. Nesciunt nemo, reiciendis laborum officia officiis aut eaque dolorem excepturi cum! Iusto corporis sapiente reprehenderit. Quia amet hic ipsam. Cum aspernatur quia nesciunt inventore, nostrum accusamus quae dolorem natus temporibus! Dolorem nihil obcaecati ea ab. Architecto alias suscipit ex odit aspernatur cumque autem magni? Quos placeat asperiores nisi cum repellat, veniam facere laborum error, necessitatibus aliquam consequatur, sapiente fuga nulla itaque! Optio delectus laudantium culpa quod aperiam repudiandae sed! Fugiat aut hic reprehenderit nulla, repudiandae ex ipsum soluta dolor optio velit similique expedita excepturi labore autem in earum quo quod quisquam dolore id atque ea dignissimos eligendi. Sapiente quod delectus eligendi! Veritatis unde maiores maxime id dicta totam culpa quae inventore assumenda. Numquam recusandae magni reiciendis quod commodi laudantium vel sint error consequuntur quas aut dolorem voluptatibus nihil quasi itaque, cum cupiditate enim voluptas doloremque. Ratione voluptates modi, veritatis alias quod totam doloremque vitae praesentium vel aliquam hic reiciendis mollitia iusto, ipsa eveniet ea autem doloribus, laborum molestiae necessitatibus nisi voluptatem facere? Harum illo similique deleniti vitae eligendi voluptatem et explicabo assumenda consequuntur, magni nostrum hic asperiores eaque provident est maiores quasi enim delectus veniam, dolorem quos quas omnis? Harum odio, accusamus quas quam corrupti non pariatur. Hic quas tempora corrupti itaque architecto possimus voluptatibus ipsa modi?
    </div>
  )
}

export default RequestCom
